# Generated by Django 3.1.7 on 2021-03-05 13:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('work_time', models.IntegerField(default=0)),
                ('work_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('brand_name', models.CharField(max_length=100)),
                ('barcode', models.IntegerField(blank=True)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_way', models.CharField(max_length=100)),
                ('point', models.IntegerField()),
                ('price', models.IntegerField()),
                ('pay_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('refund', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='store.item')),
                ('Member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='store.member')),
            ],
        ),
    ]
